#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint ||
    (
        echo '❌ ESLint Check Failed. Make the required changes listed above. Add those changes and try to commit again.'
        false
    )
echo '✅ All checks passed.'

echo '✏ Commiting your changes.'